language: java
notifications:
  slack:
    secure: mCZ+Q1KPikHGP+Z4VxkO5O+DxFElB6vwmvkVHr1y0Yg7aLFCrTaCfjBWMj1gMLURnvdIuRfF9EqBtIQT7apg48LWtxYbmEWcJgR/xzQN90fTO06EWK930QMRPdWgzqLZSb3zte46ruWrerW0VYMSFKt3I42e7AoosCMrjkQBI1k=
deploy:
  provider: releases
  api_key:
    secure: NMBpzyIeo2dmWYK2d8Pvor2i9T5qAVeddGVLgWhBlSu29XgsjZEvkFVJ0yJ6wRnW7QD1cedR0365ciH7C4faSZ+c3CUP83e0fYy08OpNSCCYpDAzBLbHCMW6mEb1+db/m/2Jry/4R+CEVRhEjEaGd/UxwnU3nFyRcMSEed3lMOM=
  file: build/libs/jenkins-plugin-1.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/jenkins-plugin
